### ISSUE TITLE
MingW64 tasks.

### ISSUE THREAD

**Issue by stuaxo** [shoebot/shoebot#318]
**Tasks blocking release**

- [x]  Update install_dependencies to include mingw64 #312
  - [x] ~~script~~
  - [x] docs
  
**Nice to haves**
- [ ] Unit tests don't run in MingW64 https://github.com/shoebot/shoebot/issues/315
- [x] ~~Sphinx docs don't build in MingW64 https://github.com/shoebot/shoebot/issues/317~~

**Other**
- [x] Gedit extension install fails in MingW64 https://github.com/shoebot/shoebot/issues/316

**Comment by stuaxo** [comment]
Closing a as it's own ticket now there's only one other task left in #315
