### ISSUE TITLE
Checklist for 1.4 release

### ISSUE THREAD

**Issue by rlafuente** [shoebot/shoebot#397]
Docs:
- [x] Clean documentation stubs
- [x] Update install docs
- [x] Update getting started
- [x] Add Atom docs
- [ ] Add video export docs
- [x] Finish changelog
- [ ] Write release announcement based on changelog
- [ ] Check if Jupyter docs are correct (I think the bit about using virtualenv is incorrect)

Home page:
- [ ] Update the home page with example screenshots

Nice-to-have:
- [x] Make screenshots for Getting started, Live variables pages
- [ ] Docs issues (the gen_index.html looks weird, can we fix it so we can use it?)

This is mostly a TODO list for me but feel free to chime in!

**Comment by stuaxo** [comment]
There's one in this ticket here (may be out of date)
https://github.com/shoebot/shoebot/issues/266

It also has a list of changes up to a point some months ago, that might make the start of a changelog.

**Comment by rlafuente** [comment]
Thanks! I looked for that issue but didn't find it and got distracted -- I'll port those over to here as a way to go through everything.

**Comment by rlafuente** [comment]
I'll use this comment for the changelog, since it's easier to edit here with the issue links.

Blocking issues (must have):
#264 #265 #274 #275 #277 #283 #285 #287 #289 #312 #247 #322

Not as important issues (should have):
#288 #290 #291 #315 #296

Outstanding from previous release (could have) #202
#155

Changes since v1.3.1:

Bugs:
- Fixed Crash when using HSB colors.
- Fixed wrong line number output in script errors.
- Fix colormode to take range, not crange for Nodebox compatibility.

Docs:
- Recommends per-user install, not system-wide.
- Update many documentation references from python to python3.
- Updated document conf to python 3.
- Remove reference to Shoebox appliance as this was not updated to python2.

Install Script and Extensions:
- Update homebrew support in Install script.
- Add homebrew to travis.
- Add options to the install script: help. output which packages will be installed.
- Manjaro, and experimental Arch support. Thanks to @villares for help and testing.
- MINGW64 support.  Thanks to @speters33w for help and testing.

Testing:
- Add OSX support to end to end tests.
- Update unit tests to use AAA style.
- Add checks to ensure travis and the install script are consistent
- Add missing packages to travis for homebrew and ubuntu.
- Add end to end tests that visual output of some examples
- Add tests for exception format.
- (Re)Add tests for color.

Libraries:
- Port various bits to pyrhon3 + remove python3isms.
- Cleanups and reformatting (including the colours library inherited from Nodebox)
- Fixes in the graph example and library
- SBVideo alert the user if numpy is not installed
- Fix the lsystem library.
- Removed the web library as was mostly bitrotted.

Examples:
- Added dendrite example from Nodebox

**Comment by stuaxo** [comment]
Re-pasted in the list of issues (I was manually putting lines through the closed tickets) - there may be more closed since then.

**Comment by stuaxo** [comment]
Small writeup on work on work to fix runs-3-times up to now, and upcoming:
https://github.com/shoebot/shoebot/issues/247#issuecomment-849208928

**Comment by stuaxo** [comment]
@rlafuente some small things have come up that make 1.4.2 worth releasing..  should we move stuff to there or keep it here ?

There's some longer term bits on here, and the things that concern me most are little bugs we've fixed, though I'm sure more stuff can go in too..

https://github.com/shoebot/shoebot/issues/437
